apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /usr/local/bin/kompose convert --file docker/docker-compose.yml --out /home/lupco/dev/dagster/.makester/k8s/manifests
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: worker
  name: worker
spec:
  ports:
    - name: "8793"
      port: 8793
      targetPort: 8793
  selector:
    io.kompose.service: worker
