apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: airflow-logs-vol
  name: airflow-logs-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
